version: '3.1'

services:

  postgres:
    image: postgres:10.4
    ports:
    - 5432:5432
    environment:
      POSTGRES_DB: retro-game
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ../sql:/docker-entrypoint-initdb.d
  redis:
    image: redis
    ports:
    - 6379:6379

