name: CI

on: [push, pull_request]

jobs:
  build-retro-game:
    name: Build retro-game (JDK ${{ matrix.java }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [11, 12, 13]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
    - name: Build with Maven
      run: mvn -B package

  build-battle-engine:
    name: Build battle engine (${{ matrix.os }}) (JDK ${{ matrix.java }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        java: [11, 12, 13]
        build: [macos, ubuntu, windows]
        include:
        - build: macos
          os: macos-latest
          cc: clang
        - build: ubuntu
          os: ubuntu-latest
          cc: gcc
        - build: windows
          os: windows-latest
          cc: gcc
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
    - name: Configure
      env:
        CC: ${{ matrix.cc }}
      run: cmake -S battle-engine -B build -G "Unix Makefiles"
    - name: Build
      run: make -C build
